import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { Palette } from "../theme";
import type { FinanceAccount, FinanceCard } from "../types";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function PayInvoiceSheet({ open, card, month, remaining, accounts, palette, onClose, onPay }: { open: boolean; card?: FinanceCard; month: string; remaining: number; accounts: FinanceAccount[]; palette: Palette; onClose: () => void; onPay: (sourceAccount: string, amount: number) => Promise<void> }) {
  const styles = useMemo(() => makeStyles(palette), [palette]); const usable = accounts.filter((item) => item.kind !== "credit-card");
  const [account, setAccount] = useState(usable[0]?.name ?? ""); const [amount, setAmount] = useState(String(remaining.toFixed(2)).replace(".", ",")); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) { setAmount(String(remaining.toFixed(2)).replace(".", ",")); setAccount(usable[0]?.name ?? ""); setError(""); } }, [open, remaining]);
  async function confirm() { const numeric = Number(amount.replace(/\./g, "").replace(",", ".")); if (!account || !Number.isFinite(numeric) || numeric <= 0 || numeric > remaining) { setError("Escolha a conta e informe um valor até o restante da fatura."); return; } setBusy(true); setError(""); try { await onPay(account, numeric); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não consegui pagar a fatura."); } finally { setBusy(false); } }
  return <Modal visible={open} transparent animationType="slide" onRequestClose={onClose}><View style={styles.layer}><Pressable style={styles.backdrop} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><Text style={styles.eyebrow}>PAGAMENTO DE FATURA</Text><Text style={styles.title}>{card?.name ?? "Cartão"}</Text><Text style={styles.copy}>Restante de {currency.format(remaining)} na competência {month.slice(5, 7)}/{month.slice(0, 4)}.</Text><Text style={styles.field}>CONTA DE PAGAMENTO</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{usable.map((item) => <Pressable key={item.id} style={[styles.chip, account === item.name && styles.chipActive]} onPress={() => setAccount(item.name)}><Text style={[styles.chipTitle, account === item.name && styles.chipTitleActive]}>{item.name}</Text><Text style={styles.chipBalance}>{currency.format(item.balance)}</Text></Pressable>)}</ScrollView><Text style={styles.field}>VALOR</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={styles.input} /><Text style={styles.note}>Ao confirmar, o valor será abatido da conta e registrado nos lançamentos como pagamento de fatura.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><Pressable style={styles.cancel} onPress={onClose}><Text style={styles.cancelText}>Cancelar</Text></Pressable><Pressable disabled={busy || !remaining} style={[styles.confirm, (busy || !remaining) && styles.disabled]} onPress={confirm}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.confirmText}>Confirmar pagamento</Text>}</Pressable></View></View></View></Modal>;
}

function makeStyles(p: Palette) { return StyleSheet.create({ layer: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,.62)" }, sheet: { padding: 21, paddingBottom: 34, borderTopLeftRadius: 29, borderTopRightRadius: 29, backgroundColor: p.surface }, handle: { width: 40, height: 4, alignSelf: "center", marginBottom: 18, borderRadius: 2, backgroundColor: p.border }, eyebrow: { color: p.accent, fontSize: 8, fontWeight: "900", letterSpacing: 1.2 }, title: { marginTop: 4, color: p.text, fontSize: 22, fontWeight: "900" }, copy: { marginTop: 5, color: p.muted, fontSize: 10 }, field: { marginTop: 17, marginBottom: 8, color: p.muted, fontSize: 8, fontWeight: "900", letterSpacing: 1 }, chips: { gap: 8, paddingRight: 20 }, chip: { minWidth: 120, padding: 12, borderRadius: 14, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface2 }, chipActive: { borderColor: p.accent, backgroundColor: p.accentSoft }, chipTitle: { color: p.text, fontSize: 10, fontWeight: "800" }, chipTitleActive: { color: p.accent }, chipBalance: { marginTop: 4, color: p.muted, fontSize: 8 }, input: { height: 60, paddingHorizontal: 15, color: p.text, fontSize: 22, fontWeight: "900", borderRadius: 16, borderWidth: 1, borderColor: p.border, backgroundColor: p.bg }, note: { marginTop: 10, color: p.muted, fontSize: 8, lineHeight: 13 }, error: { marginTop: 9, color: p.warning, fontSize: 9 }, actions: { flexDirection: "row", gap: 9, marginTop: 17 }, cancel: { flex: 1, height: 52, alignItems: "center", justifyContent: "center", borderRadius: 15, borderWidth: 1, borderColor: p.border }, cancelText: { color: p.text, fontSize: 11, fontWeight: "800" }, confirm: { flex: 1.6, height: 52, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: p.accent }, confirmText: { color: "#fff", fontSize: 11, fontWeight: "900" }, disabled: { opacity: .4 } }); }
