import { StyleSheet } from "react-native";

export type ThemeName = "dark" | "light";
export type Palette = { bg: string; surface: string; surface2: string; text: string; muted: string; border: string; accent: string; accentSoft: string; warning: string; success: string };

export const palettes: Record<ThemeName, Palette> = {
  dark: { bg: "#0b1118", surface: "#121b24", surface2: "#18242e", text: "#edf5f5", muted: "#94a7ad", border: "#273640", accent: "#35b7aa", accentSoft: "#183c3b", warning: "#ffb347", success: "#56c798" },
  light: { bg: "#ffffff", surface: "#ffffff", surface2: "#f2f7f6", text: "#142b35", muted: "#698087", border: "#e1e9ea", accent: "#0f6b68", accentSoft: "#ddefec", warning: "#d98200", success: "#288e6b" },
} as const;

export function makeStyles(p: Palette) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: p.bg }, app: { flex: 1, backgroundColor: p.bg }, content: { flex: 1 }, scroll: { padding: 20, paddingBottom: 126 }, screen: { flex: 1, padding: 20, paddingBottom: 82 }, flatList: { paddingBottom: 120 },
    headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, headerActions: { flexDirection: "row", alignItems: "center", gap: 9 }, eyebrow: { color: p.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.5 }, title: { marginTop: 4, color: p.text, fontSize: 29, fontWeight: "800", letterSpacing: -0.8 }, circleButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, circleText: { color: p.text, fontSize: 18 }, syncButton: { minWidth: 92, height: 42, paddingHorizontal: 13, alignItems: "center", justifyContent: "center", borderRadius: 14, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, syncText: { color: p.accent, fontSize: 11, fontWeight: "800" },
    connectBanner: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18, padding: 16, borderRadius: 18, borderWidth: 1, borderColor: p.accent, backgroundColor: p.accentSoft }, connectTitle: { color: p.text, fontWeight: "800", fontSize: 14 }, connectCopy: { maxWidth: 260, marginTop: 4, color: p.muted, fontSize: 11, lineHeight: 16 }, connectArrow: { color: p.accent, fontSize: 30 },
    salaryBanner: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 18, padding: 14, borderRadius: 17, backgroundColor: p.accentSoft }, salaryIcon: { width: 38, height: 38, paddingTop: 8, color: p.accent, borderRadius: 12, backgroundColor: p.surface, textAlign: "center", fontSize: 18 }, salaryTitle: { color: p.text, fontSize: 12, fontWeight: "800" }, salaryCopy: { marginTop: 3, color: p.muted, fontSize: 10 },
    sectionLabel: { marginBottom: 10, color: p.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, heroCard: { padding: 22, borderRadius: 25, backgroundColor: p.accent, shadowColor: p.accent, shadowOpacity: .22, shadowRadius: 25, elevation: 7 }, heroLabel: { color: "rgba(255,255,255,.78)", fontSize: 13, fontWeight: "700" }, heroValue: { marginTop: 8, color: "#fff", fontSize: 37, fontWeight: "900", letterSpacing: -1.4 }, heroRule: { height: 1, marginVertical: 18, backgroundColor: "rgba(255,255,255,.22)" }, heroMeta: { flexDirection: "row", justifyContent: "space-between" }, heroMetaText: { color: "rgba(255,255,255,.76)", fontSize: 10, fontWeight: "600" },
    metricsRow: { gap: 11, paddingVertical: 16, paddingRight: 20 }, metric: { width: 188, minHeight: 150, padding: 17, borderRadius: 21, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, metricWarning: { borderColor: `${p.warning}66` }, metricIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: p.accentSoft }, metricIconText: { color: p.accent, fontWeight: "900" }, metricTitle: { marginTop: 15, color: p.muted, fontSize: 11, fontWeight: "700" }, metricValue: { marginTop: 5, color: p.text, fontSize: 20, fontWeight: "800" }, metricHint: { marginTop: 5, color: p.muted, fontSize: 9 },
    sectionHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 7, marginBottom: 12 }, sectionTitle: { color: p.text, fontSize: 17, fontWeight: "800" }, sectionLink: { color: p.accent, fontSize: 11, fontWeight: "800" }, listCard: { paddingHorizontal: 15, borderRadius: 21, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface },
    transactionRow: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: p.border }, transactionIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: p.accentSoft }, transactionIncome: { backgroundColor: `${p.success}22` }, transactionIconText: { color: p.accent, fontSize: 18, fontWeight: "800" }, transactionMain: { flex: 1 }, transactionName: { color: p.text, fontSize: 13, fontWeight: "700" }, transactionMeta: { marginTop: 4, color: p.muted, fontSize: 9 }, transactionValue: { color: p.text, fontSize: 12, fontWeight: "800" }, valueIncome: { color: p.success },
    empty: { minHeight: 160, alignItems: "center", justifyContent: "center", padding: 24 }, emptyIcon: { color: p.accent, fontSize: 32 }, emptyText: { maxWidth: 250, marginTop: 10, color: p.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, screenHeader: { marginBottom: 22 },
    cardBlock: { marginBottom: 18, padding: 15, borderRadius: 24, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, cardImage: { width: "100%", aspectRatio: 1.586 }, cardStats: { flexDirection: "row", justifyContent: "space-between", gap: 16, paddingHorizontal: 7, paddingVertical: 10 }, statLabel: { color: p.muted, fontSize: 9 }, statValue: { marginTop: 4, color: p.text, fontSize: 18, fontWeight: "800" }, statValueSmall: { marginTop: 4, color: p.accent, fontSize: 12, fontWeight: "800" },
    accountGrid: { flexDirection: "row", flexWrap: "wrap", gap: 11 }, accountCard: { width: "48%", minHeight: 150, padding: 16, borderRadius: 20, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, accountMark: { width: 37, height: 37, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: p.accentSoft }, accountMarkText: { color: p.accent, fontWeight: "900" }, accountName: { marginTop: 14, color: p.muted, fontSize: 10 }, accountBalance: { marginTop: 4, color: p.text, fontSize: 17, fontWeight: "800" }, accountKind: { marginTop: 5, color: p.muted, fontSize: 8, textTransform: "capitalize" },
    settingRow: { minHeight: 76, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10, padding: 17, borderRadius: 18, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, settingTitle: { color: p.text, fontSize: 14, fontWeight: "800" }, settingCopy: { marginTop: 4, color: p.muted, fontSize: 10, lineHeight: 15 }, settingArrow: { color: p.accent, fontSize: 26 }, errorText: { marginTop: 14, color: "#ff7a88", textAlign: "center" },
    profileCard: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 14, padding: 16, borderRadius: 21, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, profileImage: { width: 58, height: 58, borderRadius: 18 }, profileImageFallback: { width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: p.accent }, profileInitial: { color: "#fff", fontSize: 21, fontWeight: "900" }, profileMain: { flex: 1 }, profileEdit: { paddingHorizontal: 11, paddingVertical: 9, borderRadius: 11, backgroundColor: p.accentSoft }, profileEditText: { color: p.accent, fontSize: 9, fontWeight: "900" },
    settingPanel: { gap: 9, marginBottom: 10, padding: 17, borderRadius: 18, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, settingSection: { marginBottom: 2, color: p.accent, fontSize: 8, fontWeight: "900", letterSpacing: 1.2 }, settingInput: { minHeight: 48, paddingHorizontal: 13, color: p.text, borderRadius: 13, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface2 }, feedbackInput: { minHeight: 94, paddingTop: 12, textAlignVertical: "top" }, settingAction: { height: 45, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: p.accent }, settingActionText: { color: "#fff", fontSize: 10, fontWeight: "900" }, feedbackHistory: { flexDirection: "row", gap: 8, paddingTop: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: p.border }, feedbackStatus: { width: 58, color: p.accent, fontSize: 7, fontWeight: "900" }, feedbackText: { flex: 1, color: p.muted, fontSize: 8, lineHeight: 12 }, developerFeedback: { gap: 7, paddingVertical: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: p.border }, feedbackStatuses: { flexDirection: "row", flexWrap: "wrap", gap: 5 }, feedbackStatusButton: { paddingHorizontal: 7, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface2 }, feedbackStatusActive: { borderColor: p.accent, backgroundColor: p.accentSoft }, feedbackStatusButtonText: { color: p.muted, fontSize: 7, fontWeight: "800" },
    tripChips: { gap: 8, paddingRight: 20, paddingBottom: 14 }, tripChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 13, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, tripChipActive: { borderColor: p.accent, backgroundColor: p.accentSoft }, tripChipText: { color: p.muted, fontSize: 9, fontWeight: "800" }, tripChipTextActive: { color: p.accent }, tripHero: { marginBottom: 14, padding: 22, borderRadius: 25, backgroundColor: p.accent, shadowColor: p.accent, shadowOpacity: .24, shadowRadius: 20, elevation: 7 }, tripEyebrow: { color: "rgba(255,255,255,.72)", fontSize: 8, fontWeight: "900", letterSpacing: 1 }, tripName: { marginTop: 7, color: "#fff", fontSize: 21, fontWeight: "900" }, tripTotal: { marginTop: 22, color: "#fff", fontSize: 34, fontWeight: "900", letterSpacing: -1 }, tripConverted: { marginTop: 5, color: "rgba(255,255,255,.75)", fontSize: 9 }, tripCategory: { minHeight: 42, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: p.border }, tripCategoryValue: { color: p.accent, fontSize: 11, fontWeight: "900" },
    fab: { position: "absolute", right: 20, bottom: 86, zIndex: 10, width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: p.accent, shadowColor: p.accent, shadowOpacity: .35, shadowRadius: 18, elevation: 9 }, fabText: { color: "#fff", fontSize: 30, lineHeight: 34 }, pressed: { transform: [{ scale: .96 }], opacity: .86 }, bottomNav: { minHeight: 72, flexDirection: "row", alignItems: "stretch", justifyContent: "space-around", paddingHorizontal: 5, borderTopWidth: 1, borderTopColor: p.border, backgroundColor: p.surface }, navItem: { position: "relative", flex: 1, minHeight: 68, alignItems: "center", justifyContent: "center", gap: 4, borderRadius: 12 }, navItemActive: { backgroundColor: p.accentSoft }, navIndicator: { position: "absolute", top: 0, width: 28, height: 3, borderBottomLeftRadius: 5, borderBottomRightRadius: 5, backgroundColor: "transparent" }, navIndicatorActive: { backgroundColor: p.accent }, navLabel: { color: p.muted, fontSize: 8, fontWeight: "700" }, navLabelActive: { color: p.accent, fontWeight: "900" },
    modalLayer: { flex: 1, justifyContent: "flex-end" }, modalBackdrop: { position: "absolute", inset: 0, backgroundColor: "rgba(0,0,0,.56)" }, composer: { padding: 20, paddingBottom: 34, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: p.surface }, composerHandle: { width: 38, height: 4, alignSelf: "center", marginBottom: 18, borderRadius: 2, backgroundColor: p.border }, composerTitle: { marginBottom: 16, color: p.text, fontSize: 21, fontWeight: "800" }, typeToggle: { flexDirection: "row", gap: 8, marginBottom: 12, padding: 4, borderRadius: 14, backgroundColor: p.surface2 }, typeButton: { flex: 1, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 11 }, typeButtonActive: { backgroundColor: p.accent }, typeText: { color: p.muted, fontSize: 12, fontWeight: "800" }, typeTextActive: { color: "#fff" }, input: { height: 52, marginBottom: 10, paddingHorizontal: 15, color: p.text, borderRadius: 15, borderWidth: 1, borderColor: p.border, backgroundColor: p.bg }, amountInput: { height: 64, fontSize: 24, fontWeight: "800" }, fieldLabel: { marginTop: 6, marginBottom: 8, color: p.muted, fontSize: 9, fontWeight: "800", letterSpacing: 1.1, textTransform: "uppercase" }, chips: { gap: 7, paddingRight: 20, paddingBottom: 8 }, chip: { minHeight: 36, justifyContent: "center", paddingHorizontal: 13, borderRadius: 12, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface2 }, chipActive: { borderColor: p.accent, backgroundColor: p.accentSoft }, chipText: { color: p.muted, fontSize: 10, fontWeight: "700" }, chipTextActive: { color: p.accent }, saveButton: { height: 54, alignItems: "center", justifyContent: "center", marginTop: 13, borderRadius: 17, backgroundColor: p.accent }, saveText: { color: "#fff", fontSize: 13, fontWeight: "800" },
    feedbackComment: { marginTop: 5, color: p.accent, fontSize: 8, lineHeight: 12 },
    notificationLayer: { flex: 1, justifyContent: "flex-end" }, notificationBackdrop: { position: "absolute", inset: 0, backgroundColor: "rgba(3,9,13,.7)" }, notificationSheet: { maxHeight: "78%", padding: 20, paddingBottom: 30, borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface }, notificationHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 15 }, notificationTitle: { color: p.text, fontSize: 22, fontWeight: "900" }, notificationSubtitle: { marginTop: 3, color: p.muted, fontSize: 10 }, notificationReadAll: { color: p.accent, fontSize: 10, fontWeight: "900" }, notificationList: { maxHeight: 430 }, notificationItem: { flexDirection: "row", gap: 11, paddingVertical: 14, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: p.border }, notificationItemUnread: { borderRadius: 15, backgroundColor: p.accentSoft }, notificationDot: { width: 8, height: 8, marginTop: 5, borderRadius: 4, backgroundColor: p.warning }, notificationDotRead: { backgroundColor: p.border }, notificationMain: { flex: 1 }, notificationItemTitle: { color: p.text, fontSize: 12, fontWeight: "900" }, notificationMessage: { marginTop: 4, color: p.muted, fontSize: 10, lineHeight: 15 }, notificationDate: { marginTop: 7, color: p.muted, fontSize: 8 }, notificationEmpty: { minHeight: 180, alignItems: "center", justifyContent: "center" }, notificationEmptyIcon: { marginBottom: 9, color: p.accent, fontSize: 30 }, notificationClose: { height: 48, alignItems: "center", justifyContent: "center", marginTop: 14, borderRadius: 14, backgroundColor: p.accent }, notificationCloseText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  });
}
