/**
 * Ícones.
 *
 * Um único lugar escolhe qual ícone representa o quê. Sem isto, uma tela usa
 * `Wallet` para conta e outra usa `Landmark`, e o produto passa a parecer
 * montado por pessoas que não se falaram.
 *
 * Traço de 1,5 px em 16 px é o par que mantém o ícone legível ao lado de texto
 * de 13–14 px sem virar mancha.
 */

export {
  ArrowDownRight,
  ArrowLeftRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Building2,
  BarChart3,
  Bell,
  Bot,
  Calendar,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  ChevronsUpDown,
  Clock,
  Copy,
  Coins,
  CreditCard,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Fuel,
  Gauge,
  Gift,
  Info,
  Landmark,
  Link2,
  ListFilter,
  Layers,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  PanelLeft,
  PanelLeftClose,
  Pause,
  Paperclip,
  Pencil,
  Percent,
  PieChart,
  PiggyBank,
  Plane,
  Plus,
  Play,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Sun,
  Target,
  Table,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Wallet,
  X,
  Zap,
} from "lucide-react";

export type { LucideIcon } from "lucide-react";
